### ISSUE TITLE
MyQ Lights

### ISSUE THREAD

**Issue by mmaxwell5** [rainlake/homebridge-platform-myq#1]
Wil, this plugin support the LiftMaster MyQ lights as well?

**Comment by rainlake** [comment]
Sorry, I do not have any MyQ light to test.

**Comment by mmaxwell5** [comment]
If I purchase one for you, will you be willing to see if you can get it supported?

**Comment by rainlake** [comment]
Hi, thanks for your generous offer, I can buy it myself. Are you talk about
823lm?

**Comment by mmaxwell5** [comment]
Yes and the 823lm.  Would no thing they are too different.,  Thank you for looking into this.

**Comment by rainlake** [comment]
got a WSLCEV from amazon, hope I will have sometime next week to make it supported. I have not figure out where should I install it though.
