### ISSUE TITLE
MyQ Light Switch & Lamp Control Modules

### ISSUE THREAD

**Issue by brianhanifin** [rainlake/homebridge-platform-myq#4]
Does this support the other [MyQ accessories](https://www.liftmaster.com/for-homes/accessories/myq-accessories)? I have both of these devices in addition to my Garage Door opener. They are [supported by an OpenHAB module](https://community.openhab.org/t/chamberlain-myq-binding/4192/). But now that iOS 10 is released I'd prefer to use my Apple TV as my smart home hub.

**Comment by rainlake** [comment]
It does support myq lights, what else do you have?

**Comment by brianhanifin** [comment]
Awesome! Heck yeah! Disabling homebridge-liftmaster2 now. :)

**Comment by rainlake** [comment]
I will close this issue. please reopen if you have more questions, thanks.
