### ISSUE TITLE
Q: why the use of `moment(...)` when calling `this.log(...)`

### ISSUE THREAD

**Issue by mrose17** [rainlake/homebridge-platform-myq#5]
it seems redundant given that the homebridge `Logger` puts out a timestamp at the beginning of entry entry. if the timestamp format isn't desirable (and i agree it isn't), wouldn't it be better to submit a PR that lets the user specify the timestamp format in "config.json" ?

just a thought.

**Comment by rainlake** [comment]
Homebridge added time stamp not long ago. That's why you see duplicate time
stamp there. I think we can remove it now.

**Comment by mrose17** [comment]
great, thank you!

**Comment by rainlake** [comment]
fixed in 0.1.5
