### ISSUE TITLE
Q: why two accessories instead of one?

### ISSUE THREAD

**Issue by mrose17** [rainlake/homebridge-platform-myq#6]
obviously, one is the controller (e.g., "CG084301....")  and the other the actual garage door, but what is the reason for making both visible to homebridge? when i use the garage door, having it open/close works fine. not so with the controller.

i'm sure i'm missing the nuance here. thanks!

**Comment by rainlake** [comment]
Actually. I figured it's not the controller. I have removed controller in
last release.
From the log file, i can see two different opener there with only few
different. I am trying to figure out what it is

**Comment by mrose17** [comment]
many thanks!

that makes sense, i'll be upgrading soon!

**Comment by rainlake** [comment]
this is related to https://github.com/rainlake/homebridge-platform-myq/issues/3#issuecomment-247247389. closing this one.
